[project]
name = "llm-ground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pypdf>=6.1.1",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
]
